### ISSUE TITLE
是否支持IE浏览器？

### ISSUE THREAD

**Issue by honghaozhilian** [pre-dem/pre-dem-web#14]
是否支持IE浏览器，最低支持到哪个版本

**Comment by lansefengxinzi** [comment]
支持 IE， IE8 以上

**Comment by honghaozhilian** [comment]
但是我看源码不是用到了document.currentScript这个html5的API来获取appkey和domain,这个API在IE浏览器下并不支持

**Comment by lansefengxinzi** [comment]
今天新更新了，支持了 IE。你下载下新的源码
